# Generated by Django 4.1 on 2022-08-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='sold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='band',
            name='types',
            field=models.CharField(choices=[('ZG', 'Zouglou'), ('CD', 'Coupe Decale'), ('SP', 'Spot')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('RC', 'Records'), ('CL', 'Clothings'), ('PS', 'Posters'), ('Ma', 'Miscellaneous')], max_length=5),
        ),
    ]
