# Generated by Django 4.1 on 2022-08-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_band_description_band_sold_band_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('ZG', 'Zouglou'), ('CD', 'Coupe Decale'), ('SP', 'Spot')], max_length=5),
        ),
        migrations.AlterField(
            model_name='band',
            name='types',
            field=models.CharField(choices=[('RC', 'Records'), ('CL', 'Clothings'), ('PS', 'Posters'), ('Ma', 'Miscellaneous')], max_length=5),
        ),
    ]
